services:

  postgresql16:
    container_name : postgresql-16
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_EFFECTIVE_CACHE_SIZE: 2GB
      POSTGRES_SHARED_BUFFERS: 1GB
      POSTGRES_WORK_MEM: 50MB
      POSTGRES_MAINTAINANCE_WORK_MEM: 128MB
    volumes:
      - data:/var/lib/postgresql/data/
    command: postgres -c 'max_connections=999'

volumes:
  data:

networks:
  default:
    external: true
    name: base
