services:

  postgresql:
    container_name : postgresql
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data/
    command: |
      postgres
      -c 'max_connections=999'
      -c 'default_toast_compression=lz4'
      -c 'shared_preload_libraries=timescaledb'
      -c 'effective_cache_size=4GB'
      -c 'shared_buffers=1GB'
      -c 'work_mem=50MB'
      -c 'maintenance_work_mem=128MB'

volumes:
  data:

networks:
  default:
    external: true
    name: base
