services:

  postgresql:
    container_name : postgresql
    build: 
      context: .
      dockerfile: Dockerfile
    shm_size: 1g
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data/
    command: |
      postgres
      -c 'max_connections=999'
      -c 'default_toast_compression=lz4'
      -c 'shared_preload_libraries=timescaledb'
      -c 'effective_cache_size=4GB'
      -c 'shared_buffers=1GB'
      -c 'work_mem=50MB'
      -c 'maintenance_work_mem=128MB'
      -c 'effective_io_concurrency=200'
      -c 'random_page_cost=1.1'
      -c 'cpu_tuple_cost=0.03'

volumes:
  data:

networks:
  default:
    external: true
    name: base
